server:
  port: 8090
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://192.168.80.154:3306/sob_blog_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
      # filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  jdbc:
    template:
      query-timeout: 3
      fetch-size: 100
      max-rows: 1000
  redis:
    url: redis://localhost:6379
    username: root
    password: 123456
    client-type: jedis
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:/com/lynnwork/sobblogsystem/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
