server:
  port: 8090
spring:
  application:
    name: sob_blog_system
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://192.168.80.154:3306/sob_blog_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
      # filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  jdbc:
    template:
      query-timeout: 3
      fetch-size: 100
      max-rows: 1000
  redis:
    # url: redis://123456@192.168.80.154:6379
    host: 192.168.80.154
    port: 6379
    password: 123456
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 465
    username: 13788809958@163.com
    password: JRuG3NnSChYaS9Lk
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          ssl:
            enable: true
mybatis-plus:
  mapper-locations: classpath:/com/lynnwork/sobblogsystem/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    com.lynnwork.sobblogsystem.mapper: debug
